system:
  addr: 127.0.0.1:7777

zap:
  release: dev
  level: debug
  format: console # 日志输出方式
  dir: log # 日志目录，todo: 分割日志
  name: temp.log

mysql:
  host: 127.0.0.1
  post: 3306
  db_name: bms
  username: root
  password: root
  max_idle_conns: 10
  max_open_conns: 50

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""